name: Build NMB for Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binary
        run: |
          go build -o nmb cmd/main.go

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: nmb_linux_amd64
          path: nmb
