name: Build NMB for Linux, macOS, and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goos: [linux, darwin, windows]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          go build -o nmb_${{ matrix.goos }}_${{ matrix.goarch }} cmd/main.go
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: nmb_${{ matrix.goos }}_${{ matrix.goarch }}
          path: nmb_${{ matrix.goos }}_${{ matrix.goarch }}
