// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlugin(arg1, arg2) {
  return window['go']['main']['App']['AddPlugin'](arg1, arg2);
}

export function ClearChanges() {
  return window['go']['main']['App']['ClearChanges']();
}

export function CreateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCategory'](arg1, arg2, arg3);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function FilterPluginsByName(arg1, arg2) {
  return window['go']['main']['App']['FilterPluginsByName'](arg1, arg2);
}

export function GetCSVPath() {
  return window['go']['main']['App']['GetCSVPath']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategoryDetails() {
  return window['go']['main']['App']['GetCategoryDetails']();
}

export function GetCategoryInfo(arg1) {
  return window['go']['main']['App']['GetCategoryInfo'](arg1);
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetNonMergedPlugins() {
  return window['go']['main']['App']['GetNonMergedPlugins']();
}

export function GetPluginNames() {
  return window['go']['main']['App']['GetPluginNames']();
}

export function GetPluginsByCategory(arg1) {
  return window['go']['main']['App']['GetPluginsByCategory'](arg1);
}

export function HasPendingChanges() {
  return window['go']['main']['App']['HasPendingChanges']();
}

export function ListImageFilesInDirectory(arg1) {
  return window['go']['main']['App']['ListImageFilesInDirectory'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function ReadImageFile(arg1) {
  return window['go']['main']['App']['ReadImageFile'](arg1);
}

export function ReadSimulationResultsFile(arg1) {
  return window['go']['main']['App']['ReadSimulationResultsFile'](arg1);
}

export function RemovePlugin(arg1, arg2) {
  return window['go']['main']['App']['RemovePlugin'](arg1, arg2);
}

export function SaveImageFile(arg1, arg2) {
  return window['go']['main']['App']['SaveImageFile'](arg1, arg2);
}

export function SelectCSVFile() {
  return window['go']['main']['App']['SelectCSVFile']();
}

export function SelectConfigFile() {
  return window['go']['main']['App']['SelectConfigFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SimulateFindings() {
  return window['go']['main']['App']['SimulateFindings']();
}

export function UpdateCSVPath(arg1) {
  return window['go']['main']['App']['UpdateCSVPath'](arg1);
}

export function UpdateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2, arg3);
}

export function ViewChanges() {
  return window['go']['main']['App']['ViewChanges']();
}

export function WriteChanges() {
  return window['go']['main']['App']['WriteChanges']();
}

export function WriteSimulationResultsToFile() {
  return window['go']['main']['App']['WriteSimulationResultsToFile']();
}
