// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';

export function AddPlugin(arg1:string,arg2:string):Promise<void>;

export function ClearChanges():Promise<void>;

export function CreateCategory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function FilterPluginsByName(arg1:string,arg2:string):Promise<Array<plugin.PluginInfo>>;

export function GetCSVPath():Promise<string>;

export function GetCategories():Promise<Array<string>>;

export function GetCategoryDetails():Promise<Array<plugin.CategoryInfo>>;

export function GetCategoryInfo(arg1:string):Promise<plugin.CategoryInfo>;

export function GetConfigPath():Promise<string>;

export function GetNonMergedPlugins():Promise<Array<plugin.PluginInfo>>;

export function GetPluginNames():Promise<{[key: string]: string}>;

export function GetPluginsByCategory(arg1:string):Promise<Array<plugin.PluginInfo>>;

export function HasPendingChanges():Promise<boolean>;

export function ListImageFilesInDirectory(arg1:string):Promise<Array<string>>;

export function OpenDirectoryDialog():Promise<string>;

export function ReadImageFile(arg1:string):Promise<string>;

export function ReadSimulationResultsFile(arg1:string):Promise<string>;

export function RemovePlugin(arg1:string,arg2:string):Promise<void>;

export function SaveImageFile(arg1:string,arg2:string):Promise<void>;

export function SelectCSVFile():Promise<string>;

export function SelectConfigFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SimulateFindings():Promise<{[key: string]: Array<plugin.PluginInfo>}>;

export function UpdateCSVPath(arg1:string):Promise<void>;

export function UpdateCategory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ViewChanges():Promise<string>;

export function WriteChanges():Promise<void>;

export function WriteSimulationResultsToFile():Promise<string>;
